version: '3.4'

services:
  jobbee.api:
    image: ${DOCKER_REGISTRY-}jobbeeapi
    container_name: jobbee.api
    build:
      context: .
      dockerfile: JobBee.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS_ACCESS_KEY_ID=AKIA6JKEYE33IENG7XUP
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - jobbee

  logstash:
    container_name: logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
    ports:
      - "2003:2003"
    environment:
      - CONFIG_SUPPORT_ESCAPE=true
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/postgresql-42.7.4.jar:/usr/share/logstash/postgresql-42.7.4.jar
    networks:
      - jobbee

networks:
  jobbee:
    driver: bridge

volumes:
  logstash_data: